### ISSUE TITLE
regeneration for file TMAP?

### ISSUE THREAD

**Issue by TeaRex73** [sean-gugler/u4remasteredA2#16]
Hello sean-gugler, have you ever attempted to do a source code regenration for the file TMAP? If I read the code correctly, it creates the Peer/View-Spell display. If you have an incomplete attempt, I'd be interested in that as well. Thanks!!

**Comment by sean-gugler** [comment]
Thanks for the prod - looks like I forgot about that file. I'll see if I can tackle it this week. Should be fun!

**Comment by sean-gugler** [comment]
Done. Release 1.2.9 now has disassembly for the TMAP file, in the branches "fixed" and "documented". Enjoy!

Doing this also reminded me about a retail flaw I'd forgotten about! It is now fixed: the view spell or peering gem now completely displays level 5 of dungeon Wrong instead of leaving some areas blank.

**Comment by TeaRex73** [comment]
Thanks for the extensive comments!
